### ISSUE TITLE
Not enough space in buffer

### ISSUE THREAD

**Issue by IcingTomato** [Sensirion/arduino-i2c-sen5x#1]
Hello, I am an Application Engineer in Seeed Studio.
I used the code from exampleUsage.
![image](https://user-images.githubusercontent.com/24474531/149705076-5236e0bc-7909-4e76-81f1-a1d2ec85c44a.png)
I have this problem in Arduino Uno.
Not enough space in buffer.
I made a usage list.

| Board | Not enough space |
| ---- | ---- |
| Arduino Uno |  Yes |
| Genuino Uno | Yes |
| Genuino 101 | Yes |
| Arduino Mega 2560 | Yes |
| Arduino Due | Yes |
| Wio Terminal(Atmel SAMD51) | Yes |
| ESP32 | No |

**Comment by psachs** [comment]
Hi,

thanks for the report. I have an Arduino Uno R3 and the example works for me.  I tested the Arduino example with multiple Arduino boards and ESP32 without any problems.
I am using the following setup:
* Arduino IDE 1.8.13
* Sensirion Core 0.5.3

Does the issue persist if you reset the board? Resp do you always have this issue or just sometimes?

Can you check if you have a stable power supply and i2c connection (e.g. no loose cables, bad contacts).

I will try to reproduce the error. Since you get I2C bus errors I suspect the "not enough space in buffer" error to be an unwanted side effect of the I2C error. This error should only occur if the specified buffers in the driver are not setup right.

Best regards,
Pascal

**Comment by IcingTomato** [comment]
Fine.
Thank you very much. The cable problem.
